server:
  port: 8181
  servlet:
    context-path: /bbc
    
management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true
      
info:
  app:
    name: BestChoiceCar
    version: 0.0.1
    description: Project For Movie Library
    author: Sumit Sharma
    
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: Pass@123

    